config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  namespace :admin do
    resources :reports  do
      collection do
        get :generate
      end
    end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: 'log_in'
    get 'log_out', to: 'devise/sessions#destroy', as: 'log_out'
    get 'sign_up', to: 'users#new', as: 'sign_up'
  end

  resources :roles
  resources :user_role_relationships
  resources :types
  resources :users do
    resources :records
  end
end

app/models/record.rb
# == Schema Information
#
# Table name: records
#
#  id         :integer          not null, primary key
#  start_time :datetime
#  end_time   :datetime
#  type_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :type

  scope :annual_leave, ->(start_date, end_date) { time_between(start_date, end_date)}
  scope :overtime, ->(start_date, end_date) {time_between(start_date, end_date)}
  scope :absence_between, -> (start_date, end_date){ time_between(start_date, end_date).where(type_id: Settings.type_id.absence )}
  scope :time_between, -> (start_date, end_date){ where("start_time >= ? AND end_time <= ?", start_date, end_date )}
  scope :of_user, ->(user_id) { where(user_id: user_id)}

  def absence?
    type_id == Settings.type_id.absence
  end

  def overtime?
    type_id == Settings.type_id.overtime
  end

  def annual_leave?
    type_id == Settings.type_id.annual_leave
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  load_and_authorize_resource

  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @records = Record.paginate(page: params[:page], per_page: 10).of_user(current_user.id)
  end

  def show
  end

  def new
    @record_form = RecordForm.new(current_user.records.new)
  end

  def edit
    @record_form = RecordForm.new(@record)
  end

  def create
    @record_form = RecordForm.new(current_user.records.new)
    if @record_form.validate(record_params)
      @record_form.save
      # @records = Record.paginate(page: params[:page], per_page: 10).of_user(current_user.id)
      # redirect_to controller: 'records', action: 'index', page: @records.total_pages
      redirect_to user_records_path(current_user), notice: "Record Created Success"
    else
      flash.now[:alert] = @record_form.errors.full_messages
      render :new
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to user_records_path(current_user, @record), notice: 'Record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to user_records_path(current_user), notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_record
    @record = current_user.records.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:start_time, :end_time, :type_id, :user_id)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record_form, { url: @record_form.url, class: 'form-horizontal' }) do |f| %>

    <div class="field">
      <%= f.label :start_time %><br>

      <div class="form-group form-inline">
        <%= f.datetime_select :start_time, {}, { class: 'form-control' } %>
      </div>
    </div>
    <div class="field">
      <div class="form-group form-inline">
        <%= f.label :end_time %><br>
        <%= f.datetime_select :end_time, {},class: 'form-control' %>
      </div>
    </div>
    <div class="field">
      <%= f.label :type_id %><br>
      <%= f.collection_select(:type_id, f.object.types, :id, :name, {prompt: 'Please Select'}, {class: 'form-control'}) %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-default' %>
    </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', user_record_path(current_user, @record) %> |
<%= link_to 'Back', user_records_path(current_user) %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <h3>
        Listing Records
      </h3>
    </div>
  </div>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Type</th>
        </tr>
        </thead>
        <tbody>
        <% @records.each do |record| %>
            <tr>
              <td><%= record.start_time.to_datetime %></td>
              <td><%= record.end_time.to_datetime %></td>
              <td><%= record.type.name %></td>
              <td><%= record.user.name %></td>
              <td><%= link_to 'Show', user_records_path(current_user) %></td>
              <td><%= link_to 'Edit', edit_user_record_path(current_user, record) %></td>
              <td><%= link_to 'Destroy', user_records_path(current_user, record), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>

        <div class="digg_pagination">
          <div class="page_info">
            <%= page_entries_info @records%>
          </div>
        <%= will_paginate @records, container: false %>
        </div>

        </tbody>
      </table>
    </div>
    <%= link_to('New Record', new_user_record_path(current_user.id)) %>
  </div>
</div>

app/views/records/new.html.erb
<div class="container">
  <div class="row clearfix">
    <h3> New Record</h3>
    <%= render 'form' %>
    <%= link_to 'Back', user_records_path(current_user) %>
  </div>
</div>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @record.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @record.end_time %>
</p>

<p>
  <strong>Type:</strong>
  <%= @record.type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @record.user_id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>