config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  namespace :admin do
    resources :reports  do
      collection do
        get :generate
      end
    end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: 'log_in'
    get 'log_out', to: 'devise/sessions#destroy', as: 'log_out'
    get 'sign_up', to: 'users#new', as: 'sign_up'
  end

  resources :roles
  resources :user_role_relationships
  resources :types
  resources :users do
    resources :records
  end
end

app/models/user_role_relationship.rb
class UserRoleRelationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/controllers/user_role_relationships_controller.rb
class UserRoleRelationshipsController < ApplicationController
  before_action :set_user_role_relationship, only: [:show, :edit, :update, :destroy]

  # GET /user_role_relationships
  # GET /user_role_relationships.json
  def index
    @user_role_relationships = UserRoleRelationship.all
  end

  # GET /user_role_relationships/1
  # GET /user_role_relationships/1.json
  def show
  end

  # GET /user_role_relationships/new
  def new
    @user_role_relationship = UserRoleRelationship.new
  end

  # GET /user_role_relationships/1/edit
  def edit
  end

  # POST /user_role_relationships
  # POST /user_role_relationships.json
  def create
    @user_role_relationship = UserRoleRelationship.new(user_role_relationship_params)

    respond_to do |format|
      if @user_role_relationship.save
        format.html { redirect_to @user_role_relationship, notice: 'User role relationship was successfully created.' }
        format.json { render :show, status: :created, location: @user_role_relationship }
      else
        format.html { render :new }
        format.json { render json: @user_role_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_role_relationships/1
  # PATCH/PUT /user_role_relationships/1.json
  def update
    respond_to do |format|
      if @user_role_relationship.update(user_role_relationship_params)
        format.html { redirect_to @user_role_relationship, notice: 'User role relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role_relationship }
      else
        format.html { render :edit }
        format.json { render json: @user_role_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_role_relationships/1
  # DELETE /user_role_relationships/1.json
  def destroy
    @user_role_relationship.destroy
    respond_to do |format|
      format.html { redirect_to user_role_relationships_url, notice: 'User role relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role_relationship
      @user_role_relationship = UserRoleRelationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_role_relationship_params
      params.require(:user_role_relationship).permit(:user_id, :role_id)
    end
end

app/helpers/user_role_relationships_helper.rb
module UserRoleRelationshipsHelper
end

app/views/user_role_relationships/_form.html.erb
<%= form_for(@user_role_relationship) do |f| %>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.number_field :user_id %>
    </div>
    <div class="field">
      <%= f.label :role_id %><br>
      <%= f.number_field :role_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/user_role_relationships/edit.html.erb
<h1>Editing User Role Relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_role_relationship %> |
<%= link_to 'Back', user_role_relationships_path %>

app/views/user_role_relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Role Relationships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_role_relationships.each do |user_role_relationship| %>
      <tr>
        <td><%= user_role_relationship.user_id %></td>
        <td><%= user_role_relationship.role_id %></td>
        <td><%= link_to 'Show', user_role_relationship %></td>
        <td><%= link_to 'Edit', edit_user_role_relationship_path(user_role_relationship) %></td>
        <td><%= link_to 'Destroy', user_role_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User role relationship', new_user_role_relationship_path %>

app/views/user_role_relationships/new.html.erb
<h1>New User Role Relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', user_role_relationships_path %>

app/views/user_role_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_role_relationship.user_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user_role_relationship.role_id %>
</p>

<%= link_to 'Edit', edit_user_role_relationship_path(@user_role_relationship) %> |
<%= link_to 'Back', user_role_relationships_path %>