config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  namespace :admin do
    resources :reports  do
      collection do
        get :generate
      end
    end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: 'log_in'
    get 'log_out', to: 'devise/sessions#destroy', as: 'log_out'
    get 'sign_up', to: 'users#new', as: 'sign_up'
  end

  resources :roles
  resources :user_role_relationships
  resources :types
  resources :users do
    resources :records
  end
end

app/views/layouts/_errors.html.erb
<% unless flash.now[:alert].blank? %>
    <div id="error_explanation">
      <% if flash.now[:alert].is_a? Array %>
          <% flash.now[:alert].each do |message| %>
              <li><%= message.to_s %></li>
          <% end %>
      <% else %>
         <li><%= flash.now[:alert] %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_header.erb
<div id="user_nav", class="right">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="#">Link</a>
            </li>
            <li>
              <a href="#">Link</a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#">Action</a>
                </li>
                <li>
                  <a href="#">Another action</a>
                </li>
                <li>
                  <a href="#">Something else here</a>
                </li>
                <li class="divider">
                </li>
                <li>
                  <a href="#">Separated link</a>
                </li>
                <li class="divider">
                </li>
                <li>
                  <a href="#">One more separated link</a>
                </li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" />
            </div> <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to('Absence', user_records_path(@user)) %>
            </li>
            <li>
              <%= link_to('Over Time', user_records_path(@user)) %>
            </li>
          </ul>
        </div>

      </nav>
      <!--<div class="jumbotron">-->
        <!--<h1>-->
          <!--Hello, world!-->
        <!--</h1>-->
        <!--<p>-->
          <!--This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.-->
        <!--</p>-->
        <!--<p>-->
          <!--<a class="btn btn-primary btn-large" href="#">Learn more</a>-->
        <!--</p>-->
      <!--</div>-->
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
          <%= link_to 'Main', user_records_path(current_user), class: 'navbar-brand' if current_user%>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to('reports', admin_reports_path)  %>
                </li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control"/>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to('Absence', new_user_record_path(current_user)) if current_user %>
            </li>
            <li>
              <%= link_to('Over Time', new_user_record_path(current_user)) if current_user%>
            </li>
            <li>
              <%= current_user ? link_to('Log out', log_out_path) : link_to("Sign Up", sign_up_path) %>
            </li>
          </ul>
        </div>


      </nav>
      <!--<div class="jumbotron">-->
      <!--<h1>-->
      <!--Hello, world!-->
      <!--</h1>-->
      <!--<p>-->
      <!--This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.-->
      <!--</p>-->
      <!--<p>-->
      <!--<a class="btn btn-primary btn-large" href="#">Learn more</a>-->
      <!--</p>-->
      <!--</div>-->
    </div>
  </div>

  <%= render partial: 'layouts/errors' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hrm</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>